# Deployment do Postgre
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre 
spec:
  selector:
    matchLabels:
      app: postgre 
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgres
          image: postgres:14.3
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "teste123"
            - name: POSTGRES_USER
              value: "teste"
            - name: POSTGRES_DB
              value: "kubenews"
---
apiVersion: v1 
kind: Service 
metadata:
  name: postgre
spec:
  selector:
    app: postgre 
  ports: 
  - port: 5432 
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: kubenews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: kubenews
        image: tognatopaulo/kube-news:latest
        env:
        - name: DB_DATABASE
          value: "kubenews"
        - name: DB_USERNAME
          value: "teste"
        - name: DB_PASSWORD
          value: "teste123"
        - name: DB_HOST
          value: "postgre"
---
apiVersion: v1 
kind: Service
metadata:
  name: kube-news 
spec: 
  selector:
    app: kubenews
  ports: 
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: LoadBalancer

